In [1]:
import pandas as pd
import numpy as np

In [2]:
###############DATI FACTSET

In [3]:
#lettura dataframe
SP_full = pd.read_csv('SP_full.csv').set_index('data')
EN_full = pd.read_csv('EN_full.csv').set_index('data')
CSI_full = pd.read_csv('CSI_full.csv').set_index('data')

In [4]:
#elimino colonna indice
del SP_full['Unnamed: 0']

In [5]:
del CSI_full['Unnamed: 0']

In [6]:
del EN_full['Unnamed: 0']

In [7]:
SP_full.head()

,A,AAL,AAP,AAPL,ABBV,ABC,ABMD,ABT,ACN,ADBE,...,XLNX,XOM,XRAY,XYL,YUM,ZBH,ZBRA,ZION,ZTS,rendimento
data,,,,,,,,,,,,,,,,,,,,,
2018-04-30,65.74,42.93,114.45,41.3150,96.55,90.58,300.95,58.13,151.20,221.60,...,64.24,77.75,50.34,72.90,87.10,115.17,134.83,54.75,83.48,2648.05
2018-05-31,61.92,43.54,128.62,46.7175,98.94,82.14,381.14,61.53,155.74,249.28,...,68.11,81.24,43.81,70.40,81.33,111.51,153.51,54.81,83.70,2705.27
2018-06-29,61.84,37.96,135.70,46.2775,92.65,85.27,409.05,60.99,163.59,243.81,...,65.26,82.73,43.77,67.38,78.22,111.44,143.25,52.69,85.19,2718.37
2018-07-31,66.04,39.54,141.23,47.5725,92.23,81.83,354.53,65.54,159.33,244.68,...,72.07,81.51,48.11,76.56,79.29,125.52,137.93,51.70,86.48,2816.29
2018-08-31,67.54,40.48,164.03,56.9075,95.98,89.97,406.58,66.84,169.07,263.51,...,77.83,80.17,39.92,75.91,86.89,123.63,171.74,53.29,90.60,2901.52

In [8]:
#creazione rendimenti percentuali dei titoli rispetto al mese precedente
rendimento_SP = SP_full.pct_change()
rendimento_EN = EN_full.pct_change()
rendimento_CSI = CSI_full.pct_change()

rendimento_SP.head()

,A,AAL,AAP,AAPL,ABBV,ABC,ABMD,ABT,ACN,ADBE,...,XLNX,XOM,XRAY,XYL,YUM,ZBH,ZBRA,ZION,ZTS,rendimento
data,,,,,,,,,,,,,,,,,,,,,
2018-04-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-05-31,-0.058108,0.014209,0.123810,0.130764,0.024754,-0.093177,0.266456,0.058490,0.030026,0.124910,...,0.060243,0.044887,-0.129718,-0.034294,-0.066246,-0.031779,0.138545,0.001096,0.002635,0.021608
2018-06-29,-0.001292,-0.128158,0.055046,-0.009418,-0.063574,0.038106,0.073228,-0.008776,0.050405,-0.021943,...,-0.041844,0.018341,-0.000913,-0.042898,-0.038239,-0.000628,-0.066836,-0.038679,0.017802,0.004842
2018-07-31,0.067917,0.041623,0.040752,0.027983,-0.004533,-0.040342,-0.133284,0.074602,-0.026041,0.003568,...,0.104352,-0.014747,0.099155,0.136242,0.013679,0.126346,-0.037138,-0.018789,0.015143,0.036022
2018-08-31,0.022714,0.023773,0.161439,0.196227,0.040659,0.099475,0.146814,0.019835,0.061131,0.076958,...,0.079922,-0.016440,-0.170235,-0.008490,0.095851,-0.015057,0.245124,0.030754,0.047641,0.030263

In [9]:
#conversione del prezzo in scala logaritmica 
SP_log = SP_full.applymap(np.log10)
EN_log = EN_full.applymap(np.log10)
CSI_log = CSI_full.applymap(np.log10)

SP_log.head()

,A,AAL,AAP,AAPL,ABBV,ABC,ABMD,ABT,ACN,ADBE,...,XLNX,XOM,XRAY,XYL,YUM,ZBH,ZBRA,ZION,ZTS,rendimento
data,,,,,,,,,,,,,,,,,,,,,
2018-04-30,1.817830,1.632761,2.058616,1.616108,1.984752,1.957032,2.478494,1.764400,2.179552,2.345570,...,1.807806,1.890700,1.701913,1.862728,1.940018,2.061339,2.129787,1.738384,1.921582,3.422926
2018-05-31,1.791831,1.638888,2.109309,1.669480,1.995372,1.914555,2.581085,1.789087,2.192400,2.396687,...,1.833211,1.909770,1.641573,1.847573,1.910251,2.047314,2.186137,1.738860,1.922725,3.432211
2018-06-29,1.791269,1.579326,2.132580,1.665370,1.966845,1.930796,2.611776,1.785259,2.213757,2.387052,...,1.814647,1.917663,1.641177,1.828531,1.893318,2.047041,2.156095,1.721728,1.930389,3.434309
2018-07-31,1.819807,1.597037,2.149927,1.677356,1.964872,1.912913,2.549653,1.816506,2.202298,2.388598,...,1.857755,1.911211,1.682235,1.884002,1.899218,2.098713,2.139659,1.713491,1.936916,3.449677
2018-08-31,1.829561,1.607241,2.214923,1.755170,1.982181,1.954098,2.609146,1.825036,2.228067,2.420797,...,1.891147,1.904012,1.601191,1.880299,1.938970,2.092124,2.234871,1.726646,1.957128,3.462626

In [10]:
#calcolo dei rendimenti logaritmici rispetto al mese precedente con eliminazione prima riga nulla
SP_rendimenti_log = SP_log.diff()[1:]
EN_rendimenti_log = EN_log.diff()[1:]
CSI_rendimenti_log = CSI_log.diff()[1:]

SP_rendimenti_log.head()

,A,AAL,AAP,AAPL,ABBV,ABC,ABMD,ABT,ACN,ADBE,...,XLNX,XOM,XRAY,XYL,YUM,ZBH,ZBRA,ZION,ZTS,rendimento
data,,,,,,,,,,,,,,,,,,,,,
2018-05-31,-0.025999,0.006128,0.050693,0.053372,0.010620,-0.042478,0.102590,0.024687,0.012848,0.051118,...,0.025405,0.019070,-0.060340,-0.015155,-0.029767,-0.014026,0.056350,0.000476,0.001143,0.009284
2018-06-29,-0.000561,-0.059562,0.023271,-0.004110,-0.028526,0.016242,0.030692,-0.003828,0.021357,-0.009636,...,-0.018564,0.007893,-0.000397,-0.019042,-0.016933,-0.000273,-0.030042,-0.017132,0.007663,0.002098
2018-07-31,0.028538,0.017710,0.017347,0.011986,-0.001973,-0.017884,-0.062123,0.031248,-0.011459,0.001547,...,0.043107,-0.006452,0.041059,0.055471,0.005901,0.051672,-0.016436,-0.008238,0.006527,0.015369
2018-08-31,0.009754,0.010204,0.064996,0.077814,0.017309,0.041185,0.059493,0.008530,0.025769,0.032199,...,0.033393,-0.007199,-0.081045,-0.003703,0.039751,-0.006589,0.095213,0.013155,0.020213,0.012948
2018-09-28,0.018874,0.009025,0.011238,-0.003621,-0.006381,0.010727,0.043825,0.040423,0.002893,0.010486,...,0.012865,0.025509,-0.024389,0.022085,0.019642,0.026703,0.012684,-0.026375,0.004578,0.001861

In [11]:
###############ESEMPIO PRIMO INVESTIMENTO MAGGIO 2019
#creazione dataset con i primi 12 mesi per regressione
df_esempio = SP_rendimenti_log[0:12]
df_esempio

,A,AAL,AAP,AAPL,ABBV,ABC,ABMD,ABT,ACN,ADBE,...,XLNX,XOM,XRAY,XYL,YUM,ZBH,ZBRA,ZION,ZTS,rendimento
data,,,,,,,,,,,,,,,,,,,,,
2018-05-31,-0.025999,0.006128,0.050693,0.053372,0.010620,-0.042478,0.102590,0.024687,0.012848,0.051118,...,0.025405,0.019070,-0.060340,-0.015155,-0.029767,-0.014026,0.056350,0.000476,0.001143,0.009284
2018-06-29,-0.000561,-0.059562,0.023271,-0.004110,-0.028526,0.016242,0.030692,-0.003828,0.021357,-0.009636,...,-0.018564,0.007893,-0.000397,-0.019042,-0.016933,-0.000273,-0.030042,-0.017132,0.007663,0.002098
2018-07-31,0.028538,0.017710,0.017347,0.011986,-0.001973,-0.017884,-0.062123,0.031248,-0.011459,0.001547,...,0.043107,-0.006452,0.041059,0.055471,0.005901,0.051672,-0.016436,-0.008238,0.006527,0.015369
2018-08-31,0.009754,0.010204,0.064996,0.077814,0.017309,0.041185,0.059493,0.008530,0.025769,0.032199,...,0.033393,-0.007199,-0.081045,-0.003703,0.039751,-0.006589,0.095213,0.013155,0.020213,0.012948
2018-09-28,0.018874,0.009025,0.011238,-0.003621,-0.006381,0.010727,0.043825,0.040423,0.002893,0.010486,...,0.012865,0.025509,-0.024389,0.022085,0.019642,0.026703,0.012684,-0.026375,0.004578,0.001861
2018-10-31,-0.036927,-0.071206,-0.022693,-0.013442,-0.084541,-0.020342,-0.119962,-0.026988,-0.033348,-0.040772,...,0.027293,-0.028172,-0.037349,-0.085612,-0.002395,-0.063487,-0.026664,-0.027711,-0.006740,-0.031239
2018-11-30,0.047931,0.058734,0.046244,-0.088334,0.083115,0.004419,-0.010982,0.031054,0.018607,0.008972,...,0.034743,-0.000982,0.037809,0.046432,0.008609,0.012920,0.033897,0.014612,0.017561,0.007688
2018-12-31,-0.030392,-0.097153,-0.052542,-0.053891,-0.009690,-0.077329,-0.010090,-0.010207,-0.066969,-0.044914,...,-0.035761,-0.066646,-0.006602,-0.038948,-0.001415,-0.052398,-0.052765,-0.077151,-0.040358,-0.041807
2019-01-31,0.052053,0.046879,0.004773,0.023316,-0.060022,0.049437,0.033457,0.003885,0.037000,0.039567,...,0.118699,0.031265,0.052072,0.028590,0.009625,0.023790,0.037525,0.067495,0.003136,0.032894
2019-02-28,0.018940,-0.001703,0.006982,0.017165,-0.005717,-0.000365,-0.020998,0.026770,0.021600,0.024993,...,0.048966,0.032807,-0.001971,0.025389,0.002396,0.054190,0.062586,0.030905,0.038884,0.012723
2019-03-29,0.005109,-0.049935,0.022876,0.040217,0.007337,-0.020169,-0.068653,0.012791,0.037712,0.006552,...,0.005134,0.009619,0.074634,0.019612,0.023742,0.012349,0.019110,-0.051269,0.028711,0.007715
2019-04-30,-0.010278,0.031892,-0.010856,0.023843,-0.006515,-0.026807,-0.012621,-0.002069,0.016105,0.035592,...,-0.023397,-0.002804,0.013282,0.023319,0.019485,-0.015721,0.003324,0.035960,0.005018,0.016747

In [12]:
#regressione dei rendimenti logaritmici mensili di tutti i titoli rispetto al rendimento logaritmico dell'indice

import statsmodels.api as sm #libreria per regressione

resids = {}
for column in df_esempio:
    
    #prima variabile: variabile dipendente (titoli)
    #seconda variabile: variabile indipendente (indice)
    reg = sm.OLS(df_esempio[column],df_esempio['rendimento']).fit() 
    resids[column] = reg.resid

In [13]:
#conversione in df dei residui
residui = pd.DataFrame(resids)
residui

,A,AAL,AAP,AAPL,ABBV,ABC,ABMD,ABT,ACN,ADBE,...,XLNX,XOM,XRAY,XYL,YUM,ZBH,ZBRA,ZION,ZTS,rendimento
data,,,,,,,,,,,,,,,,,,,,,
2018-05-31,-0.035485,-0.010591,0.040863,0.043141,0.007173,-0.051710,0.092873,0.019098,0.000702,0.038901,...,0.013189,0.009182,-0.066437,-0.028763,-0.032414,-0.025868,0.042995,-0.012859,-0.005219,0.0
2018-06-29,-0.002705,-0.063340,0.021050,-0.006422,-0.029305,0.014155,0.028496,-0.005091,0.018612,-0.012396,...,-0.021324,0.005659,-0.001774,-0.022117,-0.017531,-0.002949,-0.033060,-0.020145,0.006226,0.0
2018-07-31,0.012834,-0.009965,0.001076,-0.004950,-0.007679,-0.033167,-0.078208,0.021997,-0.031566,-0.018676,...,0.022886,-0.022819,0.030966,0.032945,0.001519,0.032069,-0.038542,-0.030311,-0.004004,0.0
2018-08-31,-0.003476,-0.013112,0.051288,0.063545,0.012501,0.028309,0.045942,0.000736,0.008829,0.015161,...,0.016356,-0.020988,-0.089548,-0.022681,0.036060,-0.023105,0.076588,-0.005441,0.011340,0.0
2018-09-28,0.016973,0.005674,0.009268,-0.005672,-0.007072,0.008877,0.041877,0.039303,0.000458,0.008037,...,0.010416,0.023527,-0.025611,0.019357,0.019111,0.024329,0.010008,-0.029048,0.003302,0.0
2018-10-31,-0.005008,-0.014954,0.010379,0.020982,-0.072943,0.010722,-0.087269,-0.008186,0.007520,0.000333,...,0.068395,0.005096,-0.016834,-0.039827,0.006510,-0.023641,0.018270,0.017154,0.014666,0.0
2018-11-30,0.040075,0.044891,0.038105,-0.096805,0.080261,-0.003226,-0.019028,0.026426,0.008550,-0.001144,...,0.024627,-0.009169,0.032761,0.035165,0.006417,0.003114,0.022839,0.003571,0.012293,0.0
2018-12-31,0.012326,-0.021870,-0.008280,-0.007820,0.005832,-0.035755,0.033665,0.014957,-0.012274,0.010098,...,0.019247,-0.022123,0.020854,0.022329,0.010503,0.000928,0.007371,-0.017107,-0.011709,0.0
2019-01-31,0.018442,-0.012355,-0.030052,-0.012933,-0.072235,0.016726,-0.000970,-0.015914,-0.006035,-0.003717,...,0.075418,-0.003766,0.030470,-0.019623,0.000248,-0.018168,-0.009790,0.020251,-0.019404,0.0
2019-02-28,0.005940,-0.024614,-0.006488,0.003144,-0.010440,-0.013017,-0.034313,0.019112,0.004955,0.008252,...,0.032226,0.019257,-0.010327,0.006741,-0.001231,0.037962,0.044286,0.012632,0.030165,0.0
2019-03-29,-0.002775,-0.063829,0.014708,0.031714,0.004472,-0.027841,-0.076728,0.008147,0.027618,-0.003601,...,-0.005018,0.001403,0.069567,0.008304,0.021543,0.002508,0.008012,-0.062350,0.023424,0.0
2019-04-30,-0.027390,0.001736,-0.028586,0.005389,-0.012733,-0.043460,-0.030147,-0.012149,-0.005804,0.013557,...,-0.045432,-0.020638,0.002284,-0.001226,0.014711,-0.037082,-0.020764,0.011908,-0.006457,0.0

In [14]:
#media dei residui relativi agli ultimi 6-1 mesi
residui_media = pd.DataFrame(residui.iloc[6:11].mean()).reset_index()

In [15]:
#ordinamento in senso crescente dei residui per trovare i titoli con media piÃ¹ alta
residui_top = residui_media.sort_values(0, ascending = False)

In [16]:
#estrazione dei 10 titoli con media dei residui piÃ¹ alta
residui_top.head(10)

    index         0
159  ENPH  0.052639
100   CMG  0.032832
167  ETSY  0.031613
260  KEYS  0.031591
496  XLNX  0.029300
498  XRAY  0.028665
53    AZO  0.027033
355  PAYC  0.026891
84   CDNS  0.026819
408   SEE  0.025549

In [17]:
#creazione del portafoglio
portafoglio = list(residui_top['index'].head(10))
portafoglio

['ENPH', 'CMG', 'ETSY', 'KEYS', 'XLNX', 'XRAY', 'AZO', 'PAYC', 'CDNS', 'SEE']

In [18]:
#rendimenti percentuali dei titoli del portafoglio nel mese di maggio
rendimento_portafoglio = rendimento_SP[portafoglio].loc['2019-05-31']
rendimento_portafoglio

ENPH    0.510956
CMG    -0.040797
ETSY   -0.077436
KEYS   -0.136734
XLNX   -0.148410
XRAY    0.053589
AZO    -0.001167
PAYC    0.047252
CDNS   -0.083742
SEE    -0.101244
Name: 2019-05-31, dtype: float64

In [19]:
#calcolo rendimento medio
rendimento_portafoglio.mean()

0.002226726056119199

In [20]:
#############AUTOMATIZZAZIONE

In [21]:
#24 mesi

mesi = ['maggio 19', 'giugno 19', 'luglio 19', 'agosto 19',
        'settembre 19', 'ottobre 19', 'novembre 19', 'dicembre 19', 
        'gennaio 20', 'febbrio 20', 'marzo 20', 'aprile 20', 
        'maggio 20', 'giugno 20', 'luglio 20', 'agosto 20', 
        'settembre 20', 'ottobre 20', 'novembre 20', 'dicembre 20', 
        'gennaio 21', 'febbrio 21', 'marzo 21', 'aprile 21']

In [22]:
###################SP500

titoli = list(SP_rendimenti_log.columns[:-1]) #lista dei titoli escludendo l'indice
portafogli_mese_SP = {} #creazione dizionario dei portafogli mensili
rendimenti_mese_SP = {} #creazione dizionario dei rendimenti dei portafogli mensili

for i in range(24): #iterazione sui 24 mesi che costituiscono i due anni di investimenti
    
    #estrazione dei rendimenti logaritmici dei 12 mesi precedenti al mese d'investimento
    df_temp = SP_rendimenti_log[0+i : 12+i] 
    
    #regressione dei rendimenti di ogni titolo sui rendimenti dell'indice
    resids = {}
    for column in titoli:
        reg = sm.OLS(df_temp[column],df_temp['rendimento']).fit()
        resids[column] = reg.resid
        
    #conversione in dataframe dei residui
    residui = pd.DataFrame(resids)

    #media dei residui degli ultimi 6-1 mesi rispetto al mese d'investimento
    residui_media = pd.DataFrame(residui.iloc[6:11].mean()).reset_index()

    #ordinamento dei titoli con media dei residui piÃ¹ alta 
    residui_top = residui_media.sort_values(0, ascending = False)

    #estrazione dei primi 10 titoli che costituiranno il portafoglio
    portafogli_mese_SP[mesi[i]] = list(residui_top['index'].head(10))

    #estrazione dei rendimenti percentuali mensili dei titoli nel portafoglio in quel mese d'investimento  
    rendimenti_mese_SP[mesi[i]] = rendimento_SP[portafogli_mese_SP[mesi[i]]].iloc[i+13]

In [23]:
###################EURONEXT

titoli = list(EN_rendimenti_log.columns[:-1]) #lista dei titoli escludendo l'indice
portafogli_mese_EN = {} #creazione dizionario dei portafogli mensili
rendimenti_mese_EN = {} #creazione dizionario dei rendimenti dei portafogli mensili

for i in range(24): #iterazione sui 24 mesi che costituiscono i due anni di investimenti
    
    #estrazione dei rendimenti logaritmici dei 12 mesi precedenti al mese d'investimento
    df_temp = EN_rendimenti_log[0+i : 12+i] 
    
    #regressione dei rendimenti di ogni titolo sui rendimenti dell'indice
    resids = {}
    for column in titoli:
        reg = sm.OLS(df_temp[column],df_temp['rendimento']).fit()
        resids[column] = reg.resid
        
    #conversione in dataframe dei residui
    residui = pd.DataFrame(resids)

    #media dei residui degli ultimi 6-1 mesi rispetto al mese d'investimento
    residui_media = pd.DataFrame(residui.iloc[6:11].mean()).reset_index()

    #ordinamento dei titoli con media dei residui piÃ¹ alta 
    residui_top = residui_media.sort_values(0, ascending = False)

    #estrazione dei primi 10 titoli che costituiranno il portafoglio
    portafogli_mese_EN[mesi[i]] = list(residui_top['index'].head(10))

    #estrazione dei rendimenti percentuali mensili dei titoli nel portafoglio in quel mese d'investimento  
    rendimenti_mese_EN[mesi[i]] = rendimento_EN[portafogli_mese_EN[mesi[i]]].iloc[i+13]

In [24]:
###################CSI300

titoli = list(CSI_rendimenti_log.columns[:-1]) #lista dei titoli escludendo l'indice
portafogli_mese_CSI = {} #creazione dizionario dei portafogli mensili
rendimenti_mese_CSI = {} #creazione dizionario dei rendimenti dei portafogli mensili

for i in range(24): #iterazione sui 24 mesi che costituiscono i due anni di investimenti
    
    #estrazione dei rendimenti logaritmici dei 12 mesi precedenti al mese d'investimento
    df_temp = CSI_rendimenti_log[0+i : 12+i] 
    
    #regressione dei rendimenti di ogni titolo sui rendimenti dell'indice
    resids = {}
    for column in titoli:
        reg = sm.OLS(df_temp[column],df_temp['rendimento']).fit()
        resids[column] = reg.resid
        
    #conversione in dataframe dei residui
    residui = pd.DataFrame(resids)

    #media dei residui degli ultimi 6-1 mesi rispetto al mese d'investimento
    residui_media = pd.DataFrame(residui.iloc[6:11].mean()).reset_index()

    #ordinamento dei titoli con media dei residui piÃ¹ alta 
    residui_top = residui_media.sort_values(0, ascending = False)

    #estrazione dei primi 10 titoli che costituiranno il portafoglio
    portafogli_mese_CSI[mesi[i]] = list(residui_top['index'].head(10))

    #estrazione dei rendimenti percentuali mensili dei titoli nel portafoglio in quel mese d'investimento  
    rendimenti_mese_CSI[mesi[i]] = rendimento_CSI[portafogli_mese_CSI[mesi[i]]].iloc[i+13]

In [25]:
portafogli_mese_SP #24 portafogli

{'maggio 19': ['ENPH',
  'CMG',
  'ETSY',
  'KEYS',
  'XLNX',
  'XRAY',
  'AZO',
  'PAYC',
  'CDNS',
  'SEE'],
 'giugno 19': ['ENPH',
  'CDNS',
  'CMG',
  'NOW',
  'QCOM',
  'PAYC',
  'MSCI',
  'XRAY',
  'MKTX',
  'KEYS'],
 'luglio 19': ['ENPH',
  'IR',
  'PAYC',
  'MKTX',
  'CPRT',
  'GPN',
  'XRAY',
  'CMG',
  'TSN',
  'CDNS'],
 'agosto 19': ['ENPH',
  'MKTX',
  'KMX',
  'CPRT',
  'QCOM',
  'CDNS',
  'XRAY',
  'GPN',
  'MSI',
  'PAYC'],
 'settembre 19': ['ENPH',
  'TTWO',
  'MKTX',
  'HSY',
  'KMX',
  'TWTR',
  'SBAC',
  'SBUX',
  'HAS',
  'GNRC'],
 'ottobre 19': ['ENPH',
  'MKTX',
  'GNRC',
  'TTWO',
  'DXCM',
  'HSY',
  'BLL',
  'RMD',
  'CME',
  'NOC'],
 'novembre 19': ['ENPH',
  'GNRC',
  'TGT',
  'AIZ',
  'RMD',
  'TTWO',
  'NOC',
  'NWL',
  'TDY',
  'EQIX'],
 'dicembre 19': ['GNRC',
  'TSLA',
  'KLAC',
  'RMD',
  'EW',
  'LEG',
  'LRCX',
  'BMY',
  'PSX',
  'NWL'],
 'gennaio 20': ['TGT',
  'DXCM',
  'CVS',
  'QRVO',
  'TSLA',
  'GNRC',
  'WU',
  'RMD',
  'TYL',
  'EW'],
 'febbrio 20': ['TGT',
  'BMY',
  'TSLA',
  'NWL',
  'AMD',
  'KR',
  'ABBV',
  'CVS',
  'QRVO',
  'CNC'],
 'marzo 20': ['TSLA',
  'PENN',
  'CZR',
  'DXCM',
  'AMD',
  'DPZ',
  'CNC',
  'ENPH',
  'GE',
  'BMY'],
 'aprile 20': ['TSLA',
  'ENPH',
  'DXCM',
  'PENN',
  'REGN',
  'AMD',
  'NVDA',
  'DPZ',
  'NFLX',
  'QRVO'],
 'maggio 20': ['TSLA',
  'DXCM',
  'ENPH',
  'REGN',
  'DVA',
  'NVDA',
  'AMD',
  'FTNT',
  'NFLX',
  'NOW'],
 'giugno 20': ['TSLA',
  'ENPH',
  'ETSY',
  'NEM',
  'DXCM',
  'CTLT',
  'AMZN',
  'NVDA',
  'AMD',
  'REGN'],
 'luglio 20': ['ENPH',
  'TSLA',
  'ETSY',
  'DXCM',
  'PENN',
  'REGN',
  'PYPL',
  'NVDA',
  'WST',
  'CTLT'],
 'agosto 20': ['ETSY',
  'REGN',
  'TSLA',
  'DXCM',
  'NVDA',
  'EBAY',
  'PYPL',
  'ENPH',
  'WST',
  'TSCO'],
 'settembre 20': ['ABMD',
  'WST',
  'ETSY',
  'TSLA',
  'PYPL',
  'MPWR',
  'AMZN',
  'AMD',
  'CDNS',
  'CTLT'],
 'ottobre 20': ['TSLA',
  'ETSY',
  'NVDA',
  'GNRC',
  'UPS',
  'WST',
  'PYPL',
  'ENPH',
  'AMD',
  'ABMD'],
 'novembre 20': ['PENN',
  'LB',
  'TSLA',
  'GNRC',
  'FDX',
  'NVDA',
  'UPS',
  'POOL',
  'FBHS',
  'GPS'],
 'dicembre 20': ['TSLA',
  'FDX',
  'GPS',
  'GNRC',
  'LB',
  'FCX',
  'ALGN',
  'PWR',
  'UPS',
  'IVZ'],
 'gennaio 21': ['ENPH',
  'FDX',
  'LB',
  'TSLA',
  'TPR',
  'GNRC',
  'PWR',
  'AMD',
  'DE',
  'ALGN'],
 'febbrio 21': ['ENPH',
  'TPR',
  'TSLA',
  'GE',
  'PWR',
  'HWM',
  'PENN',
  'ALGN',
  'FCX',
  'IVZ'],
 'marzo 21': ['ENPH',
  'TPR',
  'IVZ',
  'DISCA',
  'UAA',
  'ALGN',
  'MU',
  'GE',
  'ALB',
  'PENN'],
 'aprile 21': ['TPR',
  'DISCA',
  'OXY',
  'DISCK',
  'GE',
  'VIAC',
  'IVZ',
  'MRO',
  'UAA',
  'MU']}

In [26]:
portafogli_mese_EN #24 portafogli

{'maggio 19': ['BNHKYX',
  'BYQ7HZ',
  '550507',
  '595607',
  '405780',
  '567151',
  '468232',
  'BD0Q39',
  '483477',
  '406141'],
 'giugno 19': ['BYQ7HZ',
  '516529',
  'BNHKYX',
  '406141',
  '550507',
  '449123',
  'B4PH0C',
  'B1Y1SQ',
  '533004',
  'B62G1B'],
 'luglio 19': ['BZ1HM4',
  'BYQ7HZ',
  'B0HZL9',
  'BNHKYX',
  '516529',
  'BF0LBX',
  'B4PH0C',
  '449123',
  '401225',
  '406141'],
 'agosto 19': ['BYQ7HZ',
  '449123',
  'BNHKYX',
  '406141',
  '474171',
  '779255',
  'B62G1B',
  'BNFWR4',
  'B0HZL9',
  '483410'],
 'settembre 19': ['516529',
  'BYYHL2',
  'BYQ7HZ',
  'BNFWR4',
  'B929F4',
  '406141',
  '599933',
  '403187',
  'B3B8D0',
  '598662'],
 'ottobre 19': ['516529',
  '721247',
  'BYQ7HZ',
  '599933',
  '596233',
  'B929F4',
  'B3B8D0',
  'BNFWR4',
  'B1Y9TB',
  '598662'],
 'novembre 19': ['516529',
  'B929F4',
  '721247',
  '599933',
  'BWT6H8',
  'B3B8D0',
  'B0C2CQ',
  '598662',
  'B058TZ',
  'B1Y9TB'],
 'dicembre 19': ['516529',
  'BWT6H8',
  '721247',
  '596233',
  'BF4446',
  'B929F4',
  '400212',
  'B0C2CQ',
  'B39GNW',
  '599933'],
 'gennaio 20': ['516529',
  'BWT6H8',
  '596233',
  'BF4446',
  'BYTBXV',
  'B929F4',
  '596651',
  '721247',
  'BNDPYV',
  '599933'],
 'febbrio 20': ['BWT6H8',
  'BF4446',
  'BYTBXV',
  '775943',
  '596651',
  'BNDPYV',
  '596233',
  '516529',
  'B929F4',
  '410359'],
 'marzo 20': ['BYTBXV',
  '596233',
  '516529',
  'BF4446',
  '449123',
  '410359',
  '775943',
  'BWT6H8',
  'BZ1HM4',
  '559699'],
 'aprile 20': ['596233',
  '775943',
  'B0NJJ1',
  '449123',
  'BZ1HM4',
  '516529',
  'BYTBXV',
  '559699',
  'BNFWR4',
  'B39GNW'],
 'maggio 20': ['596233',
  'BZ1HM4',
  'BNHKYX',
  'BNFWR4',
  '775943',
  'B1L3CS',
  '516529',
  'BF4446',
  '449123',
  'BWT6H8'],
 'giugno 20': ['BZ1HM4',
  'BWT6H8',
  'BYQ7HZ',
  '596233',
  'BNFWR4',
  'BF4446',
  'BF0LBX',
  '410359',
  'B929F4',
  'BNHKYX'],
 'luglio 20': ['BZ1HM4',
  'BNHKYX',
  'BF0LBX',
  '775943',
  'BYQ7HZ',
  '559699',
  'BWT6H8',
  'BNDPYV',
  'BNFWR4',
  '516529'],
 'agosto 20': ['BZ1HM4',
  'BNHKYX',
  '775943',
  '516529',
  'BNFWR4',
  'B929F4',
  'BWT6H8',
  '479213',
  'BF0LBX',
  '559699'],
 'settembre 20': ['BZ1HM4',
  'BF0LBX',
  'BNHKYX',
  '474171',
  'BWT6H8',
  '775943',
  '559699',
  'B0HZL9',
  '516529',
  'BNDPYV'],
 'ottobre 20': ['BZ1HM4',
  'BNHKYX',
  '474171',
  'BF0LBX',
  'BWT6H8',
  'BNDPYV',
  '775943',
  '449123',
  'BJDS7L',
  'B0HZL9'],
 'novembre 20': ['BZ1HM4',
  '474171',
  'BNHKYX',
  '449123',
  'BNDPYV',
  'BF0LBX',
  'B3B8D0',
  'B39GNW',
  'B0HZL9',
  '738048'],
 'dicembre 20': ['B3B8D0',
  '474171',
  'B39GNW',
  '449123',
  'BYPBS6',
  'BWT6H8',
  'BZ1HM4',
  'B0HZL9',
  '483477',
  '599933'],
 'gennaio 21': ['B39GNW',
  'B3B8D0',
  'BYPBS6',
  '449123',
  'B0NJJ1',
  '474171',
  'BWT6H8',
  'BNDPYV',
  '596233',
  'B86S2N'],
 'febbrio 21': ['BYPBS6',
  'B39GNW',
  '406141',
  'B11HK3',
  'B929F4',
  'B1RR82',
  'B86S2N',
  'BNDPYV',
  'B3B8D0',
  'BZ1HM4'],
 'marzo 21': ['B39GNW',
  '516529',
  'BYPBS6',
  'B929F4',
  'BFYM46',
  '438042',
  'B1RR82',
  'B1L3CS',
  'B1HDJL',
  '596233'],
 'aprile 21': ['B1HDJL',
  '516529',
  '438042',
  'BFYM46',
  'B11HK3',
  '596651',
  'B09CBL',
  'BYPBS6',
  '595607',
  'B929F4']}

In [27]:
portafogli_mese_CSI #24 portafogli

{'maggio 19': ['B23N9L',
  'BJ0JR2',
  '600394',
  '603759',
  'B4ZW31',
  'B40JZ1',
  'B4TSW2',
  '667328',
  'B66DNR',
  '664882'],
 'giugno 19': ['600394',
  'B23N9L',
  '603759',
  '667328',
  'BJ0JR2',
  'BD3H4Q',
  '679872',
  '612877',
  'BF04KS',
  'B4ZW31'],
 'luglio 19': ['600394',
  'B23N9L',
  '603759',
  'BG1VQ3',
  'BJ0JR2',
  '674381',
  'B6SGJ8',
  'B4ZW31',
  '611209',
  '609145'],
 'agosto 19': ['603759',
  'B23N9L',
  '600394',
  'B4ZW31',
  'BD3H4Q',
  'B6SGJ8',
  '611291',
  'BDHTRS',
  '609145',
  '611209'],
 'settembre 19': ['600394',
  'BD3H4Q',
  '603759',
  'BJ0JR2',
  '611291',
  'BZ07VX',
  '610990',
  'B23N9L',
  '612877',
  '651748'],
 'ottobre 19': ['BZ07VX',
  'B4YB1F',
  'BD3H4Q',
  '612877',
  '668346',
  'B6SGJ8',
  '610990',
  '645084',
  '651748',
  'B4TSW2'],
 'novembre 19': ['B4YB1F',
  '645084',
  'BZ07VX',
  'BYM9X7',
  'B2R9WZ',
  '612877',
  'B6SGJ8',
  'BF2W0K',
  'BD3H4Q',
  '611209'],
 'dicembre 19': ['BZ07VX',
  'B4YB1F',
  'B2R9WZ',
  '645084',
  'BYM9X7',
  'BW9LDQ',
  'B64QPN',
  'BF2W0K',
  'B4XT6X',
  'BFXR91'],
 'gennaio 20': ['645084',
  'BZ07VX',
  'B2R9WZ',
  'BYM9X7',
  'BW9LDQ',
  '626836',
  'B64QPN',
  'B6SGJ8',
  'B24G11',
  'BFXR91'],
 'febbrio 20': ['645084',
  'BYM9X7',
  'BZ07VX',
  'B1H6P8',
  'B24G11',
  'B44DPG',
  '626836',
  'B3XCR3',
  'BW9LDQ',
  'B6SGJ8'],
 'marzo 20': ['645084',
  'BW9LDQ',
  'BYM9X7',
  'B41CNM',
  'B44DPG',
  '661651',
  'BZ6S21',
  '677351',
  'BV8SL2',
  'B66DNR'],
 'aprile 20': ['BYM9X7',
  'B66DNR',
  'B41CNM',
  'B4TSW2',
  'B40JZ1',
  '645084',
  'B44DPG',
  'B72TPR',
  'BW9LDQ',
  '626836'],
 'maggio 20': ['BFXXPY',
  'B41CNM',
  'B44DPG',
  'B66DNR',
  'BYM9X7',
  'B72TPR',
  'B4TSW2',
  'BV86QT',
  'B40JZ1',
  'B4PT3T'],
 'giugno 20': ['B40JZ1',
  'B66DNR',
  'BFXXPY',
  'B3PNJB',
  'BDZVZJ',
  'BDHTRS',
  'B1VKWZ',
  '634667',
  'B44DPG',
  'BYM9X7'],
 'luglio 20': ['B40JZ1',
  'B66DNR',
  'BDZVZJ',
  'B3TRP3',
  'B3PNJB',
  '680282',
  'BDHTRS',
  'BZHJN9',
  'B1VKWZ',
  '634667'],
 'agosto 20': ['BDZVZJ',
  'B5B40S',
  'B42G7J',
  'B01KM0',
  '634667',
  '619530',
  'B3TRP3',
  'BJ0JR2',
  'B3YR78',
  '603759'],
 'settembre 20': ['B3PNJB',
  'B5B40S',
  'B42G7J',
  '699988',
  '619530',
  'B01KM0',
  '612118',
  '690285',
  'BDZVZJ',
  '680836'],
 'ottobre 20': ['609145',
  '680836',
  '699988',
  '690285',
  'B759P5',
  'BJ3KJC',
  'BZHJN9',
  'B4W4ZY',
  'B42G7J',
  '680282'],
 'novembre 20': ['B3WXMX',
  'B759P5',
  'B46632',
  'B42G7J',
  '609145',
  '680836',
  'BJ3KJC',
  'B3P1NF',
  '663216',
  '651748'],
 'dicembre 20': ['B3WXMX',
  'B46632',
  'B759P5',
  'B3P1NF',
  '651748',
  '635353',
  'B4W4ZY',
  '609145',
  'B02FVZ',
  'B1YQ5Q'],
 'gennaio 21': ['B3WXMX',
  '619394',
  'B1YQ5Q',
  'B46632',
  '608697',
  '635353',
  'B4TPTS',
  '651748',
  'B4PT3T',
  'BD3NFF'],
 'febbrio 21': ['B1YQ5Q',
  'B3WXMX',
  '619394',
  'B46632',
  '680836',
  'B4PT3T',
  '635353',
  'B28T7X',
  '651748',
  'B41CNM'],
 'marzo 21': ['B46632',
  'B3WXMX',
  'B41CNM',
  'B1YQ5Q',
  'BV8SL2',
  '635353',
  '664882',
  'B4TSW2',
  'B4PT3T',
  'BZ07VX'],
 'aprile 21': ['BV8SL2',
  'B1YQ5Q',
  '643455',
  '604201',
  'B41CNM',
  '630795',
  'B1P13B',
  '600551',
  'BZ07VX',
  'BKDQFP']}

In [28]:
rendimenti_mese_SP #rendimenti mensili dei 24 portafogli

{'maggio 19': ENPH    0.510956
 CMG    -0.040797
 ETSY   -0.077436
 KEYS   -0.136734
 XLNX   -0.148410
 XRAY    0.053589
 AZO    -0.001167
 PAYC    0.047252
 CDNS   -0.083742
 SEE    -0.101244
 Name: 2019-05-31, dtype: float64,
 'giugno 19': ENPH    0.201714
 CDNS    0.113890
 CMG     0.110475
 NOW     0.048257
 QCOM    0.138432
 PAYC    0.068930
 MSCI    0.085360
 XRAY    0.083349
 MKTX    0.079242
 KEYS    0.195395
 Name: 2019-06-28, dtype: float64,
 'luglio 19': ENPH    0.544158
 IR     -0.047110
 PAYC    0.061882
 MKTX    0.048597
 CPRT    0.037329
 GPN     0.048648
 XRAY   -0.066998
 CMG     0.085485
 TSN    -0.015358
 CDNS    0.043779
 Name: 2019-07-31, dtype: float64,
 'agosto 19': ENPH    0.053996
 MKTX    0.179741
 KMX    -0.051048
 CPRT   -0.027602
 QCOM    0.063013
 CDNS   -0.073468
 XRAY   -0.042241
 GPN    -0.011553
 MSI     0.090082
 PAYC    0.038920
 Name: 2019-08-30, dtype: float64,
 'settembre 19': ENPH   -0.250758
 TTWO   -0.050239
 MKTX   -0.176349
 HSY    -0.022022
 KMX     0.056676
 TWTR   -0.033998
 SBAC   -0.081088
 SBUX   -0.084300
 HAS     0.074409
 GNRC    0.004488
 Name: 2019-09-30, dtype: float64,
 'ottobre 19': ENPH   -0.125956
 MKTX    0.125466
 GNRC    0.232831
 TTWO   -0.039812
 DXCM    0.033503
 HSY    -0.052390
 BLL    -0.039006
 RMD     0.094812
 CME    -0.026450
 NOC    -0.059527
 Name: 2019-10-31, dtype: float64,
 'novembre 19': ENPH    0.125579
 GNRC    0.019880
 TGT     0.169301
 AIZ     0.053938
 RMD     0.011357
 TTWO    0.008309
 NOC    -0.002014
 NWL     0.013179
 TDY     0.037591
 EQIX    0.000124
 Name: 2019-11-29, dtype: float64,
 'dicembre 19': GNRC    0.021218
 TSLA    0.267897
 KLAC    0.087331
 RMD     0.035896
 EW     -0.047563
 LEG    -0.028479
 LRCX    0.095829
 BMY     0.127327
 PSX    -0.028853
 NWL     0.000000
 Name: 2019-12-31, dtype: float64,
 'gennaio 20': TGT    -0.136261
 DXCM    0.100622
 CVS    -0.087091
 QRVO   -0.089220
 TSLA    0.555160
 GNRC    0.029824
 WU      0.004481
 RMD     0.025811
 TYL     0.078861
 EW     -0.057568
 Name: 2020-01-31, dtype: float64,
 'febbrio 20': TGT    -0.069893
 BMY    -0.061795
 TSLA    0.026777
 NWL    -0.209933
 AMD    -0.032340
 KR      0.047282
 ABBV    0.057887
 CVS    -0.127396
 QRVO   -0.049877
 CNC    -0.155867
 Name: 2020-02-28, dtype: float64,
 'marzo 20': TSLA   -0.215557
 PENN   -0.572202
 CZR    -0.713033
 DXCM   -0.024384
 AMD     0.000000
 DPZ    -0.045337
 CNC     0.120521
 ENPH   -0.340617
 GE     -0.270221
 BMY    -0.056214
 Name: 2020-03-31, dtype: float64,
 'aprile 20': TSLA    0.492137
 ENPH    0.450294
 DXCM    0.244847
 PENN    0.408696
 REGN    0.076983
 AMD     0.151935
 NVDA    0.108801
 DPZ     0.116827
 NFLX    0.118109
 QRVO    0.215801
 Name: 2020-04-30, dtype: float64,
 'maggio 20': TSLA    0.067939
 DXCM    0.128610
 ENPH    0.242580
 REGN    0.165304
 DVA     0.024680
 NVDA    0.214657
 AMD     0.026914
 FTNT    0.291999
 NFLX   -0.000286
 NOW     0.103516
 Name: 2020-05-29, dtype: float64,
 'giugno 20': TSLA    0.293186
 ENPH   -0.182506
 ETSY    0.311805
 NEM     0.055926
 DXCM    0.071608
 CTLT   -0.056992
 AMZN    0.129567
 NVDA    0.070109
 AMD    -0.022119
 REGN    0.017689
 Name: 2020-06-30, dtype: float64,
 'luglio 20': ENPH    0.268867
 TSLA    0.325011
 ETSY    0.114374
 DXCM    0.074346
 PENN    0.108382
 REGN    0.013501
 PYPL    0.125352
 NVDA    0.117607
 WST     0.183563
 CTLT    0.191542
 Name: 2020-07-31, dtype: float64,
 'agosto 20': ETSY    0.011151
 REGN   -0.019207
 TSLA    0.741452
 DXCM   -0.023258
 NVDA    0.259992
 EBAY   -0.009045
 PYPL    0.041159
 ENPH    0.279490
 WST     0.056124
 TSCO    0.042665
 Name: 2020-08-31, dtype: float64,
 'settembre 20': ABMD   -0.099343
 WST    -0.031906
 ETSY    0.016124
 TSLA   -0.139087
 PYPL   -0.034829
 MPWR    0.046719
 AMZN   -0.087579
 AMD    -0.097225
 CDNS   -0.038590
 CTLT   -0.073946
 Name: 2020-09-30, dtype: float64,
 'ottobre 20': TSLA   -0.095499
 ETSY   -0.000329
 NVDA   -0.073648
 GNRC    0.085261
 UPS    -0.057133
 WST    -0.010295
 PYPL   -0.055322
 ENPH    0.187674
 AMD    -0.081717
 ABMD   -0.090883
 Name: 2020-10-30, dtype: float64,
 'novembre 20': PENN    0.296777
 LB      0.212434
 TSLA    0.462736
 GNRC    0.025934
 FDX     0.104482
 NVDA    0.069212
 UPS     0.088855
 POOL   -0.010634
 FBHS    0.032521
 GPS     0.077635
 Name: 2020-11-30, dtype: float64,
 'dicembre 20': TSLA    0.243252
 FDX    -0.094075
 GPS    -0.036737
 GNRC    0.054777
 LB     -0.041742
 FCX     0.112441
 ALGN    0.110308
 PWR     0.053848
 UPS    -0.015608
 IVZ     0.073937
 Name: 2020-12-31, dtype: float64,
 'gennaio 21': ENPH    0.039209
 FDX    -0.093521
 LB      0.095994
 TSLA    0.124506
 TPR     0.017375
 GNRC    0.083594
 PWR    -0.021522
 AMD    -0.066187
 DE      0.073406
 ALGN   -0.016842
 Name: 2021-01-29, dtype: float64,
 'febbrio 21': ENPH   -0.034494
 TPR     0.332701
 TSLA   -0.148740
 GE      0.174157
 PWR     0.189868
 HWM     0.143613
 PENN    0.116275
 ALGN    0.079428
 FCX     0.260126
 IVZ     0.088878
 Name: 2021-02-26, dtype: float64,
 'marzo 21': ENPH    -0.078950
 TPR     -0.022069
 IVZ      0.124888
 DISCA   -0.180464
 UAA      0.012334
 ALGN    -0.045106
 MU      -0.036272
 GE       0.047049
 ALB     -0.070606
 PENN    -0.094490
 Name: 2021-03-31, dtype: float64,
 'aprile 21': TPR      0.161126
 DISCA   -0.133456
 OXY     -0.047333
 DISCK   -0.124153
 GE      -0.000762
 VIAC    -0.090466
 IVZ      0.070579
 MRO      0.054307
 UAA      0.097022
 MU      -0.024260
 Name: 2021-04-30, dtype: float64}

In [29]:
rendimenti_mese_EN

{'maggio 19': BNHKYX   -0.035270
 BYQ7HZ    0.026744
 550507   -0.120854
 595607   -0.004939
 405780   -0.024733
 567151    0.000091
 468232    0.010015
 BD0Q39   -0.067059
 483477   -0.072544
 406141   -0.035435
 Name: 2019-05-31, dtype: float64,
 'giugno 19': BYQ7HZ    0.063232
 516529    0.117150
 BNHKYX    0.136310
 406141    0.129688
 550507    0.140705
 449123    0.046033
 B4PH0C    0.034838
 B1Y1SQ    0.062444
 533004    0.079250
 B62G1B    0.120887
 Name: 2019-06-28, dtype: float64,
 'luglio 19': BZ1HM4   -0.010202
 BYQ7HZ   -0.036543
 B0HZL9    0.014573
 BNHKYX    0.008646
 516529    0.263867
 BF0LBX    0.027352
 B4PH0C   -0.025511
 449123   -0.093134
 401225    0.004201
 406141   -0.019692
 Name: 2019-07-31, dtype: float64,
 'agosto 19': BYQ7HZ    0.057910
 449123   -0.072535
 BNHKYX   -0.080172
 406141   -0.044910
 474171    0.014941
 779255   -0.014579
 B62G1B   -0.035727
 BNFWR4   -0.041440
 B0HZL9   -0.008282
 483410   -0.035234
 Name: 2019-08-30, dtype: float64,
 'settembre 19': 516529    0.094091
 BYYHL2    0.003977
 BYQ7HZ   -0.165625
 BNFWR4   -0.087277
 B929F4    0.112335
 406141   -0.003888
 599933   -0.008539
 403187    0.058695
 B3B8D0    0.010992
 598662   -0.018921
 Name: 2019-09-30, dtype: float64,
 'ottobre 19': 516529    0.090937
 721247    0.058552
 BYQ7HZ    0.020548
 599933    0.045468
 596233    0.173989
 B929F4    0.058244
 B3B8D0   -0.008580
 BNFWR4   -0.037632
 B1Y9TB   -0.058452
 598662   -0.054430
 Name: 2019-10-31, dtype: float64,
 'novembre 19': 516529    0.107808
 B929F4    0.038769
 721247    0.018645
 599933    0.045694
 BWT6H8    0.109733
 B3B8D0   -0.049886
 B0C2CQ   -0.053549
 598662    0.060658
 B058TZ    0.034287
 B1Y9TB   -0.006913
 Name: 2019-11-29, dtype: float64,
 'dicembre 19': 516529    0.009981
 BWT6H8    0.060630
 721247   -0.019497
 596233    0.094288
 BF4446    0.132442
 B929F4    0.086880
 400212    0.040012
 B0C2CQ    0.020884
 B39GNW    0.074322
 599933    0.029413
 Name: 2019-12-31, dtype: float64,
 'gennaio 20': 516529    0.084853
 BWT6H8   -0.066043
 596233    0.041628
 BF4446   -0.053496
 BYTBXV    0.005481
 B929F4   -0.048119
 596651   -0.069718
 721247   -0.024008
 BNDPYV   -0.029120
 599933    0.029948
 Name: 2020-01-31, dtype: float64,
 'febbrio 20': BWT6H8   -0.071848
 BF4446   -0.099406
 BYTBXV   -0.184753
 775943    0.054666
 596651   -0.132084
 BNDPYV   -0.072431
 596233   -0.043288
 516529   -0.054733
 B929F4   -0.032774
 410359   -0.075404
 Name: 2020-02-28, dtype: float64,
 'marzo 20': BYTBXV   -0.249454
 596233   -0.186674
 516529   -0.130632
 BF4446   -0.157659
 449123   -0.147295
 410359   -0.134122
 775943   -0.022051
 BWT6H8   -0.140969
 BZ1HM4   -0.034423
 559699   -0.055604
 Name: 2020-03-31, dtype: float64,
 'aprile 20': 596233    0.190836
 775943    0.097924
 B0NJJ1    0.010447
 449123   -0.046871
 BZ1HM4    0.167400
 516529    0.097783
 BYTBXV    0.127445
 559699    0.055589
 BNFWR4    0.152139
 B39GNW    0.018224
 Name: 2020-04-30, dtype: float64,
 'maggio 20': 596233   -0.053823
 BZ1HM4    0.333128
 BNHKYX    0.414407
 BNFWR4    0.099788
 775943    0.182836
 B1L3CS    0.041584
 516529    0.057018
 BF4446    0.026647
 449123    0.213220
 BWT6H8    0.048298
 Name: 2020-05-29, dtype: float64,
 'giugno 20': BZ1HM4    0.105730
 BWT6H8    0.024596
 BYQ7HZ   -0.039969
 596233    0.106155
 BNFWR4    0.159541
 BF4446    0.062172
 BF0LBX   -0.043475
 410359    0.016165
 B929F4    0.126724
 BNHKYX    0.045563
 Name: 2020-06-30, dtype: float64,
 'luglio 20': BZ1HM4    0.151585
 BNHKYX    0.037445
 BF0LBX    0.183694
 775943    0.008886
 BYQ7HZ    0.041492
 559699    0.111560
 BWT6H8    0.154977
 BNDPYV    0.040026
 BNFWR4   -0.006711
 516529   -0.020638
 Name: 2020-07-31, dtype: float64,
 'agosto 20': BZ1HM4    0.008519
 BNHKYX    0.002575
 775943    0.087957
 516529   -0.003249
 BNFWR4    0.071178
 B929F4    0.060644
 BWT6H8    0.113418
 479213    0.061907
 BF0LBX   -0.065858
 559699   -0.075315
 Name: 2020-08-31, dtype: float64,
 'settembre 20': BZ1HM4    0.091199
 BF0LBX    0.033018
 BNHKYX    0.138959
 474171    0.107793
 BWT6H8   -0.058342
 775943   -0.139719
 559699   -0.044311
 B0HZL9    0.025368
 516529   -0.048641
 BNDPYV   -0.013935
 Name: 2020-09-30, dtype: float64,
 'ottobre 20': BZ1HM4   -0.085614
 BNHKYX   -0.053449
 474171   -0.075510
 BF0LBX   -0.051196
 BWT6H8    0.094733
 BNDPYV    0.005703
 775943    0.049957
 449123   -0.043087
 BJDS7L    0.082712
 B0HZL9   -0.028907
 Name: 2020-10-30, dtype: float64,
 'novembre 20': BZ1HM4    0.136522
 474171    0.055242
 BNHKYX    0.145698
 449123    0.003590
 BNDPYV    0.022108
 BF0LBX   -0.029334
 B3B8D0    0.054023
 B39GNW    0.117523
 B0HZL9    0.025793
 738048    0.220647
 Name: 2020-11-30, dtype: float64,
 'dicembre 20': B3B8D0    0.028252
 474171    0.045518
 B39GNW    0.313136
 449123   -0.197370
 BYPBS6    0.258089
 BWT6H8    0.097852
 BZ1HM4    0.216327
 B0HZL9    0.048938
 483477    0.071611
 599933   -0.006078
 Name: 2020-12-31, dtype: float64,
 'gennaio 21': B39GNW   -0.017957
 B3B8D0    0.037619
 BYPBS6   -0.051141
 449123   -0.031287
 B0NJJ1   -0.208428
 474171   -0.001854
 BWT6H8   -0.084707
 BNDPYV    0.145567
 596233    0.090977
 B86S2N   -0.036461
 Name: 2021-01-29, dtype: float64,
 'febbrio 21': BYPBS6    0.071969
 B39GNW   -0.198066
 406141    0.052628
 B11HK3    0.250548
 B929F4    0.057978
 B1RR82   -0.013998
 B86S2N    0.097610
 BNDPYV   -0.070809
 B3B8D0    0.016778
 BZ1HM4    0.113268
 Name: 2021-02-26, dtype: float64,
 'marzo 21': B39GNW   -0.025299
 516529    0.073944
 BYPBS6    0.231985
 B929F4    0.075753
 BFYM46    0.088003
 438042    0.038100
 B1RR82   -0.006992
 B1L3CS   -0.070404
 B1HDJL   -0.020683
 596233   -0.015969
 Name: 2021-03-31, dtype: float64,
 'aprile 21': B1HDJL    0.019733
 516529    0.044486
 438042    0.060070
 BFYM46    0.027996
 B11HK3   -0.002560
 596651    0.086443
 B09CBL   -0.034279
 BYPBS6    0.008447
 595607    0.014339
 B929F4    0.072193
 Name: 2021-04-30, dtype: float64}

In [30]:
rendimenti_mese_CSI

{'maggio 19': B23N9L   -0.101434
 BJ0JR2   -0.035495
 600394   -0.193271
 603759    0.161411
 B4ZW31   -0.094390
 B40JZ1    0.083811
 B4TSW2   -0.059730
 667328   -0.203789
 B66DNR    0.067581
 664882   -0.038417
 Name: 2019-05-31, dtype: float64,
 'giugno 19': 600394   -0.162457
 B23N9L   -0.185595
 603759   -0.152536
 667328   -0.043472
 BJ0JR2   -0.067293
 BD3H4Q    0.241777
 679872   -0.093910
 612877    0.069734
 BF04KS    0.207077
 B4ZW31    0.170043
 Name: 2019-06-28, dtype: float64,
 'luglio 19': 600394   -0.031134
 B23N9L    0.145990
 603759    0.111207
 BG1VQ3   -0.082942
 BJ0JR2    0.299688
 674381    0.032975
 B6SGJ8    0.031145
 B4ZW31   -0.072169
 611209   -0.079154
 609145   -0.054180
 Name: 2019-07-31, dtype: float64,
 'agosto 19': 603759   -0.028392
 B23N9L   -0.018235
 600394   -0.121806
 B4ZW31   -0.061954
 BD3H4Q    0.178441
 B6SGJ8    0.317342
 611291   -0.065188
 BDHTRS    0.152257
 609145    0.134228
 611209    0.082445
 Name: 2019-08-30, dtype: float64,
 'settembre 19': 600394   -0.009855
 BD3H4Q    0.033433
 603759   -0.119088
 BJ0JR2   -0.122287
 611291   -0.094109
 BZ07VX    0.115204
 610990   -0.081799
 B23N9L   -0.224379
 612877    0.024799
 651748   -0.119505
 Name: 2019-09-30, dtype: float64,
 'ottobre 19': BZ07VX    0.137502
 B4YB1F   -0.101733
 BD3H4Q   -0.092111
 612877   -0.084627
 668346   -0.048531
 B6SGJ8    0.104614
 610990    0.032463
 645084    0.079374
 651748    0.038214
 B4TSW2    0.232326
 Name: 2019-10-31, dtype: float64,
 'novembre 19': B4YB1F    0.038197
 645084    0.290196
 BZ07VX    0.139727
 BYM9X7    0.075875
 B2R9WZ    0.044917
 612877    0.019512
 B6SGJ8    0.028779
 BF2W0K   -0.017233
 BD3H4Q    0.067834
 611209    0.026852
 Name: 2019-11-29, dtype: float64,
 'dicembre 19': BZ07VX    0.155365
 B4YB1F   -0.003830
 B2R9WZ    0.036301
 645084   -0.037076
 BYM9X7    0.249567
 BW9LDQ    0.086565
 B64QPN    0.081945
 BF2W0K   -0.018822
 B4XT6X    0.160652
 BFXR91   -0.083160
 Name: 2019-12-31, dtype: float64,
 'gennaio 20': 645084    0.358313
 BZ07VX    0.300599
 B2R9WZ    0.191347
 BYM9X7    0.388344
 BW9LDQ    0.504091
 626836   -0.062794
 B64QPN    0.243359
 B6SGJ8    0.200623
 B24G11   -0.138292
 BFXR91    0.118875
 Name: 2020-01-31, dtype: float64,
 'febbrio 20': 645084    0.105389
 BYM9X7    0.271815
 BZ07VX   -0.069121
 B1H6P8   -0.204982
 B24G11   -0.090499
 B44DPG    0.035772
 626836    0.265006
 B3XCR3    0.023505
 BW9LDQ   -0.066592
 B6SGJ8   -0.133276
 Name: 2020-02-28, dtype: float64,
 'marzo 20': 645084   -0.282308
 BW9LDQ   -0.263053
 BYM9X7   -0.343069
 B41CNM   -0.236919
 B44DPG   -0.049460
 661651   -0.271549
 BZ6S21   -0.282101
 677351   -0.234416
 BV8SL2   -0.233064
 B66DNR   -0.225663
 Name: 2020-03-31, dtype: float64,
 'aprile 20': BYM9X7    0.154643
 B66DNR    0.316034
 B41CNM    0.157248
 B4TSW2    0.168343
 B40JZ1    0.218599
 645084    0.057442
 B44DPG    0.113602
 B72TPR    0.000314
 BW9LDQ    0.262103
 626836    0.089532
 Name: 2020-04-30, dtype: float64,
 'maggio 20': BFXXPY   -0.013085
 B41CNM    0.054897
 B44DPG   -0.072038
 B66DNR   -0.014187
 BYM9X7   -0.038214
 B72TPR   -0.082789
 B4TSW2   -0.050661
 BV86QT    0.125839
 B40JZ1    0.110249
 B4PT3T    0.046358
 Name: 2020-05-29, dtype: float64,
 'giugno 20': B40JZ1    0.093024
 B66DNR    0.135773
 BFXXPY    0.048308
 B3PNJB    0.207187
 BDZVZJ    0.306069
 BDHTRS    0.121911
 B1VKWZ    0.292707
 634667    0.276382
 B44DPG    0.390383
 BYM9X7    0.232196
 Name: 2020-06-30, dtype: float64,
 'luglio 20': B40JZ1    0.350367
 B66DNR    0.236416
 BDZVZJ    0.067121
 B3TRP3    0.112874
 B3PNJB    0.882387
 680282    0.222338
 BDHTRS    0.405450
 BZHJN9   -0.089261
 B1VKWZ    0.097942
 634667    0.080664
 Name: 2020-07-31, dtype: float64,
 'agosto 20': BDZVZJ   -0.091288
 B5B40S   -0.200406
 B42G7J   -0.128461
 B01KM0   -0.096753
 634667   -0.092463
 619530   -0.042039
 B3TRP3   -0.072944
 BJ0JR2   -0.022768
 B3YR78    0.137660
 603759    0.189769
 Name: 2020-08-31, dtype: float64,
 'settembre 20': B3PNJB    0.037470
 B5B40S   -0.193540
 B42G7J    0.078783
 699988   -0.192094
 619530   -0.204365
 B01KM0   -0.004169
 612118   -0.098345
 690285   -0.134644
 BDZVZJ   -0.011029
 680836    0.011440
 Name: 2020-09-30, dtype: float64,
 'ottobre 20': 609145    0.071463
 680836    0.154596
 699988   -0.024648
 690285    0.072098
 B759P5    0.029757
 BJ3KJC    0.004563
 BZHJN9    0.057524
 B4W4ZY    0.230764
 B42G7J   -0.090852
 680282   -0.107316
 Name: 2020-10-30, dtype: float64,
 'novembre 20': B3WXMX    0.196880
 B759P5   -0.079726
 B46632    0.096528
 B42G7J   -0.013723
 609145   -0.052432
 680836    0.088285
 BJ3KJC    0.011573
 B3P1NF   -0.016495
 663216   -0.072101
 651748    0.081835
 Name: 2020-11-30, dtype: float64,
 'dicembre 20': B3WXMX    0.364473
 B46632    0.135984
 B759P5    0.350768
 B3P1NF    0.110025
 651748    0.241620
 635353    0.206023
 B4W4ZY    0.231626
 609145    0.327258
 B02FVZ    0.024123
 B1YQ5Q    0.238827
 Name: 2020-12-31, dtype: float64,
 'gennaio 21': B3WXMX    0.122258
 619394   -0.202431
 B1YQ5Q    0.028808
 B46632    0.286774
 608697   -0.091315
 635353    0.242902
 B4TPTS    0.253828
 651748    0.153392
 B4PT3T    0.049581
 BD3NFF   -0.002698
 Name: 2021-01-29, dtype: float64,
 'febbrio 21': B1YQ5Q    0.018660
 B3WXMX   -0.251577
 619394    0.052915
 B46632   -0.201237
 680836   -0.163670
 B4PT3T   -0.189112
 635353   -0.197358
 B28T7X   -0.009518
 651748   -0.087159
 B41CNM   -0.173353
 Name: 2021-02-26, dtype: float64,
 'marzo 21': B46632   -0.178153
 B3WXMX   -0.053448
 B41CNM   -0.061867
 B1YQ5Q    0.054119
 BV8SL2   -0.241731
 635353   -0.040926
 664882   -0.181341
 B4TSW2   -0.133791
 B4PT3T   -0.072067
 BZ07VX   -0.105946
 Name: 2021-03-31, dtype: float64,
 'aprile 21': BV8SL2    0.204903
 B1YQ5Q    0.369516
 643455    0.216216
 604201    0.078063
 B41CNM    0.176562
 630795    0.081850
 B1P13B   -0.085907
 600551   -0.089425
 BZ07VX    0.193570
 BKDQFP   -0.121691
 Name: 2021-04-30, dtype: float64}

In [37]:
#calcolo della media dei rendimenti ##################
rendimento_medio_SP={}
for i in mesi:
    rendimento_medio_SP[i] = rendimenti_mese_SP[i].mean()
    
rendimento_medio_EN={}
for i in mesi:
    rendimento_medio_EN[i] = rendimenti_mese_EN[i].mean()
    
rendimento_medio_CSI={}
for i in mesi:
    rendimento_medio_CSI[i] = rendimenti_mese_CSI[i].mean()

In [38]:
rendimento_medio_SP

{'maggio 19': 0.002226726056119199,
 'giugno 19': 0.11250430565147349,
 'luglio 19': 0.07404127942326869,
 'agosto 19': 0.021984031744216637,
 'settembre 19': -0.056318050992221404,
 'ottobre 19': 0.014347094105972635,
 'novembre 19': 0.04372439812240305,
 'dicembre 19': 0.05306036778290427,
 'gennaio 20': 0.04246197840111203,
 'febbrio 20': -0.05751568610979622,
 'marzo 20': -0.21170432785772714,
 'aprile 20': 0.23844298855629303,
 'maggio 20': 0.1265912544805605,
 'giugno 20': 0.06882729984076463,
 'luglio 20': 0.15225450273434232,
 'agosto 20': 0.13805218008804473,
 'settembre 20': -0.05396627550004668,
 'ottobre 20': -0.01918897376522758,
 'novembre 20': 0.13599513113977987,
 'dicembre 20': 0.04604030839420068,
 'gennaio 21': 0.023601083298735448,
 'febbrio 21': 0.12018115568413909,
 'marzo 21': -0.03436850984454667,
 'aprile 21': -0.003739568277005134}

In [39]:
rendimento_medio_EN

{'maggio 19': -0.032398396738578916,
 'giugno 19': 0.09305368064306371,
 'luglio 19': 0.013355810589076977,
 'agosto 19': -0.02600279034319016,
 'settembre 19': -0.0004160221077494808,
 'ottobre 19': 0.0288644617117652,
 'novembre 19': 0.03052471907473344,
 'dicembre 19': 0.05293538241752956,
 'gennaio 20': -0.012859473956996114,
 'febbrio 20': -0.07120546843487399,
 'marzo 20': -0.12588841576835538,
 'aprile 20': 0.08709153234412736,
 'maggio 20': 0.13631032569184381,
 'giugno 20': 0.05632019920436816,
 'luglio 20': 0.0702316133671468,
 'agosto 20': 0.026177536153631064,
 'settembre 20': 0.00913892592388189,
 'ottobre 20': -0.010465922547471584,
 'novembre 20': 0.07518129896373661,
 'dicembre 20': 0.08762763137379087,
 'gennaio 21': -0.015767324578558818,
 'febbrio 21': 0.037790627398083185,
 'marzo 21': 0.03684378197871051,
 'aprile 21': 0.02968673845760539}

In [40]:
rendimento_medio_CSI

{'maggio 19': -0.04137216515531718,
 'giugno 19': -0.0016631650512772156,
 'luglio 19': 0.030142502800541336,
 'agosto 19': 0.05691390695003169,
 'settembre 19': -0.059758550122007634,
 'ottobre 19': 0.029748973789740084,
 'novembre 19': 0.07146564800093694,
 'dicembre 19': 0.06275067468532831,
 'gennaio 20': 0.21044651021988797,
 'febbrio 20': 0.013701785230720232,
 'marzo 20': -0.2421601541125828,
 'aprile 20': 0.153786071610512,
 'maggio 20': 0.006636979889904282,
 'giugno 20': 0.21039395896743257,
 'luglio 20': 0.2366296108162731,
 'agosto 20': -0.04196930191957373,
 'settembre 20': -0.07104932083852902,
 'ottobre 20': 0.03979487706433932,
 'novembre 20': 0.024062268276794963,
 'dicembre 20': 0.22307280650531686,
 'gennaio 21': 0.08410978068746691,
 'febbrio 21': -0.12014094766910963,
 'marzo 21': -0.10151507097469378,
 'aprile 21': 0.1023658918923613}

In [41]:
rendimento_tot_SP = 1
for i in mesi:
    rendimento_tot_SP *= (1 + rendimento_medio_SP[i])
    
rendimento_tot_EN = 1
for i in mesi:
    rendimento_tot_EN *= (1 + rendimento_medio_EN[i])

rendimento_tot_CSI = 1
for i in mesi:
    rendimento_tot_CSI *= (1 + rendimento_medio_CSI[i])

In [42]:
rendimento_tot_SP

2.3718557472813337

In [43]:
rendimento_tot_EN

1.7036853383437134

In [44]:
rendimento_tot_CSI

2.0335910682510656